# Generated by Django 5.0.3 on 2024-08-12 19:07

import KingsWayApp.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Application",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(max_length=100)),
                (
                    "middle_name",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("last_name", models.CharField(max_length=100)),
                ("address", models.TextField()),
                ("city", models.CharField(max_length=100)),
                ("country", models.CharField(max_length=100)),
                ("district", models.CharField(blank=True, max_length=100, null=True)),
                ("dob", models.DateField()),
                ("email", models.EmailField(max_length=100)),
                ("primary_phone", models.CharField(max_length=15)),
                (
                    "secondary_phone",
                    models.CharField(blank=True, max_length=15, null=True),
                ),
                ("someone_else", models.BooleanField()),
                (
                    "treatment_centre",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("age", models.BooleanField()),
                ("abuse_problem", models.BooleanField()),
                ("faith_based", models.BooleanField()),
                ("commitment", models.BooleanField()),
                ("forced", models.BooleanField()),
                ("disabilities", models.BooleanField()),
                ("psychiatric", models.BooleanField()),
                ("aids", models.BooleanField()),
                ("medications", models.BooleanField()),
                ("medications_details", models.TextField(blank=True, null=True)),
                ("warrants", models.BooleanField()),
                ("parole", models.BooleanField()),
                ("detention", models.BooleanField()),
                ("legal_issues", models.BooleanField()),
                ("legal_issues_details", models.TextField(blank=True, null=True)),
                ("sex_offender", models.BooleanField()),
                ("comments", models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Donation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=10)),
                ("name", models.CharField(max_length=255)),
                ("email", models.EmailField(max_length=254)),
                (
                    "payment_method",
                    models.CharField(
                        choices=[
                            ("credit_card", "Credit Card"),
                            ("paypal", "PayPal"),
                            ("bank_transfer", "Bank Transfer"),
                        ],
                        max_length=50,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("full_name", models.CharField(max_length=100)),
                ("item_name", models.CharField(max_length=255)),
                (
                    "quantity",
                    models.PositiveIntegerField(
                        validators=[django.core.validators.MinValueValidator(1)]
                    ),
                ),
                ("email", models.EmailField(max_length=254)),
                (
                    "phone_number",
                    models.CharField(
                        help_text="Enter your phone number with country code, e.g., +256700633321",
                        max_length=16,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Phone number must be entered in the format: '+123456789'. Up to 15 digits allowed.",
                                regex="^\\+?\\d{7,15}$",
                            )
                        ],
                    ),
                ),
                ("delivery_address", models.CharField(max_length=100)),
                (
                    "payment_option",
                    models.CharField(
                        choices=[
                            ("Cash-On-Delivery", "Cash on Delivery"),
                            ("Mobile_Money", "Mobile Money"),
                        ],
                        max_length=30,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Subscription",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        validators=[KingsWayApp.models.validate_name],
                    ),
                ),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("subscribed_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
