# Generated by Django 5.1 on 2024-08-15 13:33

import KingsWayApp.models
import django.core.validators
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('KingsWayApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='application',
            name='id_number',
        ),
        migrations.AddField(
            model_name='application',
            name='address',
            field=models.CharField(default=django.utils.timezone.now, max_length=100, validators=[django.core.validators.MinLengthValidator(4)]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='application',
            name='nin',
            field=models.CharField(default=django.utils.timezone.now, max_length=20, validators=[KingsWayApp.models.nin_validator]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='application',
            name='surname_name',
            field=models.CharField(default=django.utils.timezone.now, max_length=100, validators=[KingsWayApp.models.validate_name, django.core.validators.MinLengthValidator(2)]),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='application',
            name='other_names',
            field=models.CharField(max_length=200, validators=[KingsWayApp.models.validate_name, django.core.validators.MinLengthValidator(2)]),
        ),
        migrations.AlterField(
            model_name='application',
            name='physical_address',
            field=models.CharField(max_length=100, validators=[django.core.validators.MinLengthValidator(4)]),
        ),
    ]
