# Generated by Django 5.0.3 on 2024-08-12 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("KingsWayApp", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="order",
            name="email",
        ),
        migrations.AddField(
            model_name="order",
            name="item_size",
            field=models.CharField(
                choices=[
                    ("small", "Small"),
                    ("medium", "Medium"),
                    ("large", "Large"),
                    ("extra_large", "Extra Large"),
                ],
                default="medium",
                max_length=20,
            ),
        ),
    ]
