# Generated by Django 5.0.7 on 2024-08-13 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("KingsWayApp", "0002_remove_order_email_order_item_size"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="item_size",
            field=models.CharField(
                blank=True,
                choices=[
                    ("XS", "Extra Small"),
                    ("S", "Small"),
                    ("M", "Medium"),
                    ("L", "Large"),
                    ("XL", "Extra Large"),
                ],
                max_length=2,
                null=True,
            ),
        ),
    ]
