# Generated by Django 5.1 on 2024-08-15 14:53

import KingsWayApp.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('KingsWayApp', '0002_remove_application_id_number_application_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='address',
            field=models.CharField(max_length=100, validators=[KingsWayApp.models.validate_name, django.core.validators.MinLengthValidator(4)]),
        ),
        migrations.AlterField(
            model_name='application',
            name='nationality',
            field=models.CharField(max_length=100, validators=[KingsWayApp.models.validate_name, django.core.validators.MinLengthValidator(4)]),
        ),
        migrations.AlterField(
            model_name='application',
            name='physical_address',
            field=models.CharField(max_length=100, validators=[KingsWayApp.models.validate_name, django.core.validators.MinLengthValidator(4)]),
        ),
    ]
