# Generated by Django 5.1 on 2024-08-15 15:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('KingsWayApp', '0004_application_emergency_phone_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='application',
            name='emergency_phone_number',
        ),
    ]
