# Generated by Django 5.1 on 2024-08-15 15:15

import django.core.validators
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('KingsWayApp', '0005_remove_application_emergency_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='emergency_phone_number',
            field=models.CharField(default=django.utils.timezone.now, max_length=17, validators=[django.core.validators.RegexValidator(message='Enter a valid phone number.', regex='^\\+?1?\\d{9,15}$')]),
            preserve_default=False,
        ),
    ]
