# Generated by Django 5.1 on 2024-08-15 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('KingsWayApp', '0006_application_emergency_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='nin',
            field=models.CharField(max_length=20),
        ),
    ]
