# Generated by Django 5.1 on 2024-08-15 15:57

import multiselectfield.db.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('KingsWayApp', '0007_alter_application_nin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='marital_status',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('Single', 'Single'), ('Married', 'Married'), ('Divorced', 'Divorced')], max_length=23),
        ),
    ]
